services:
  db:
    image: postgres:17
    env_file: 
      - .env
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    image: ghcr.io/ttimco3/internship-tracker-backend:latest
    env_file: 
      - backend/.env
    ports: 
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: ghcr.io/ttimco3/internship-tracker-frontend:latest
    ports: 
      - "5173:80"
    depends_on:
      backend:
        condition: service_started
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: nickfedor/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --label-enable

volumes:
  postgres_data:
